from django.conf import settings
from django.db import models

# Create your models here.

class Game(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class WarhammerCharacter(models.Model):
    name = models.CharField(max_length=200)
    kin = models.CharField(max_length=200)
    gender = models.CharField(max_length=200)
    vocation = models.CharField(max_length=200)
    alignment = models.CharField(max_length=200)
    age = models.CharField(max_length=20)
    size = models.CharField(max_length=20)
    weight = models.CharField(max_length=20)
    hair = models.CharField(max_length=20)
    eyes = models.CharField(max_length=20)
    description = models.CharField(max_length=100)
    current_career = models.CharField(max_length=200)
    career_path =  models.CharField(max_length=500)
    career_exits =  models.CharField(max_length=500)
    m_starter_profile = models.IntegerField()
    m_advance_scheme = models.IntegerField()
    m_current_profile = models.IntegerField()
    ws_starter_profile = models.IntegerField()
    ws_advance_scheme = models.IntegerField()
    ws_current_profile = models.IntegerField()
    bs_starter_profile = models.IntegerField()
    bs_advance_scheme = models.IntegerField()
    bs_current_profile = models.IntegerField()
    s_starter_profile = models.IntegerField()
    s_advance_scheme = models.IntegerField()
    s_current_profile = models.IntegerField()
    t_starter_profile = models.IntegerField()
    t_advance_scheme = models.IntegerField()
    t_current_profile = models.IntegerField()
    w_starter_profile = models.IntegerField()
    w_advance_scheme = models.IntegerField()
    w_current_profile = models.IntegerField()
    i_starter_profile = models.IntegerField()
    i_advance_scheme = models.IntegerField()
    i_current_profile = models.IntegerField()
    a_starter_profile = models.IntegerField()
    a_advance_scheme = models.IntegerField()
    a_current_profile = models.IntegerField()
    dex_starter_profile = models.IntegerField()
    dex_advance_scheme = models.IntegerField()
    dex_current_profile = models.IntegerField()
    ld_starter_profile = models.IntegerField()
    ld_advance_scheme = models.IntegerField()
    ld_current_profile = models.IntegerField()
    int_starter_profile = models.IntegerField()
    int_advance_scheme = models.IntegerField()
    int_current_profile = models.IntegerField()
    cl_starter_profile = models.IntegerField()
    cl_advance_scheme = models.IntegerField()
    cl_current_profile = models.IntegerField()
    wp_starter_profile = models.IntegerField()
    wp_advance_scheme = models.IntegerField()
    wp_current_profile = models.IntegerField()
    fel_starter_profile = models.IntegerField()
    fel_advance_scheme = models.IntegerField()
    fel_current_profile = models.IntegerField()
    fate_points = models.IntegerField()
    magic_points = models.IntegerField()
    power_level = models.IntegerField()
    experience = models.IntegerField()
    owner = models.ManyToManyField(settings.AUTH_USER_MODEL)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
